# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-16 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Name')),
                ('bra', models.CharField(blank=True, choices=[('ME-II', 'ME-II'), ('ME-III', 'ME-III'), ('ME-IV', 'ME-IV'), ('PE-II', 'PE-II'), ('PE-III', 'PE-III'), ('PE-IV', 'PE-IVI')], max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=10, validators=[profiles.models.validate])),
            ],
        ),
    ]
